/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type AlertEvent struct {
	// A locally unique, system-generated name. The name cannot be modified.
	Name string `json:"name,omitempty"`
	// Actual condition at the time the alert is created.
	Actual string `json:"actual,omitempty"`
	Alert *AlertEventAlert `json:"alert,omitempty"`
	// The parent alert number.
	Code int64 `json:"code,omitempty"`
	// The component type of the alert.
	ComponentName string `json:"component_name,omitempty"`
	// The component name of the alert.
	ComponentType string `json:"component_type,omitempty"`
	// The time the parent alert was created.
	Created int64 `json:"created,omitempty"`
	// Expected state and threshold under normal conditions.
	Expected string `json:"expected,omitempty"`
	// Information about the alert cause.
	Issue string `json:"issue,omitempty"`
	// The knowledge base URL of the alert.
	KnowledgeBaseUrl string `json:"knowledge_base_url,omitempty"`
	// The severity level of the alert. Valid values include `info`, `warning`, `critical`, and `hidden`.
	Severity string `json:"severity,omitempty"`
	// The state of the alert. Valid values include `open`, `closing`, and `closed`.
	State string `json:"state,omitempty"`
	// A summary of the alert.
	Summary string `json:"summary,omitempty"`
	// The time the event occurred.
	Time int64 `json:"time,omitempty"`
}
