/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28VolumesnapshotPatchBody struct {
	// If set to true, destroys a resource. Once set to true, the time_remaining value will display the amount of time left until the destroyed resource is permanently eradicated. Before the time_remaining period has elapsed, the destroyed resource can be recovered by setting destroyed=false. Once the time_remaining period has elapsed, the resource is permanently eradicated and can no longer be recovered.
	Destroyed bool `json:"destroyed,omitempty"`
	// The new name for the resource.
	Name string `json:"name,omitempty"`
}
