/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type MemberNoIdGroup struct {
	Group *Api28certificatescertificatesigningrequestsCertificate `json:"group,omitempty"`
	Member *Api28hostsPreferredArrays `json:"member,omitempty"`
}
