/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// The policy to which this rule belongs.
type AllOfPolicyRuleQuotaPolicy struct {
	// A globally unique, system-generated ID. The ID cannot be modified.
	Id string `json:"id,omitempty"`
	// The resource name, such as volume name, pod name, snapshot name, and so on.
	Name string `json:"name,omitempty"`
	// Type of the object (full name of the endpoint). Valid values include `hosts`, `host-groups`, `network-interfaces`, `pods`, `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`, `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, `policies/snapshot`, and `policies/quota`.
	ResourceType string `json:"resource_type,omitempty"`
}
