/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// The snapshot policy that manages this snapshot. Set to `name` or `id` to `\"\"` to clear the policy.
type Api28directorysnapshotsPolicy struct {
	// A globally unique, system-generated ID. The ID cannot be modified.
	Id string `json:"id,omitempty"`
	// The resource name, such as volume name, pod name, snapshot name, and so on.
	Name string `json:"name,omitempty"`
}
