/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type SoftwareInstallationStepsChecks struct {
	// Detailed result of the check used to diagnose check failures.
	Details string `json:"details,omitempty"`
	// Name of the upgrade check.
	Name string `json:"name,omitempty"`
	// Whether the check failure can be overridden.
	Overridable bool `json:"overridable,omitempty"`
	// Status of the check. Valid values are `running`, `failed`, `passed`, and `overridden`. A status of `running` indicates that the check has not finished. A status of `failed` indicates that the check has failed. A status of `passed` indicates that the check has passed. A status of `overridden` indicates that the check has failed, but the failure has been overridden.
	Status string `json:"status,omitempty"`
}
