/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28SupportBody struct {
	// The status of phonehome. If set to `true`, enable phonehome. If set to `false`, disable phonehome.
	PhonehomeEnabled bool `json:"phonehome_enabled,omitempty"`
	// The value of the current proxy, which is used for connecting to cloud services such as phonehome, remote assist, etc. Specify the server name, including the scheme and proxy port number.
	Proxy string `json:"proxy,omitempty"`
	// The status of a remote assist session. If set to `true`, enable the remote assist session. If set to `false`, disable the remote assist session.
	RemoteAssistActive bool `json:"remote_assist_active,omitempty"`
}
