/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// An individual node of a Purity app. Nodes are indexed starting at `0`.
type AppNode struct {
	App *AppNodeApp `json:"app,omitempty"`
	// An index that represents this node.
	Index int32 `json:"index,omitempty"`
	// The node status. Possible values are `starting`, `healthy`, `unhealthy`, `critical`, `stopping`, and `disabled`.
	Status string `json:"status,omitempty"`
	// The node version.
	Version string `json:"version,omitempty"`
	// The VNC information used to access this node if VNC is enabled.
	Vnc []string `json:"vnc,omitempty"`
}
