/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28DirectoryexportsBody struct {
	// The name of the export to create. Export names must be unique within the same protocol.
	ExportName string `json:"export_name,omitempty"`
}
