/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type HostGroup struct {
	// A user-specified name. The name must be locally unique and can be changed.
	Name string `json:"name,omitempty"`
	// The number of volumes connected to the host group.
	ConnectionCount int64 `json:"connection_count,omitempty"`
	// The number of hosts in the host group.
	HostCount int64 `json:"host_count,omitempty"`
	// Returns a value of `true` if the host or host group belongs to the current array. Returns a value of `false` if the host or host group belongs to a remote array.
	IsLocal bool `json:"is_local,omitempty"`
	Space *DirectorySpaceSpace `json:"space,omitempty"`
}
