/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type NetworkInterfacePerformance struct {
	// A user-specified name. The name must be locally unique and can be changed.
	Name string `json:"name,omitempty"`
	// The interface type. Valid values are `eth` and `fc`.
	InterfaceType string `json:"interface_type,omitempty"`
	// Sample time in milliseconds since UNIX epoch.
	Time int64 `json:"time,omitempty"`
	Eth *NetworkInterfacePerformanceEth `json:"eth,omitempty"`
	Fc *NetworkInterfacePerformanceFc `json:"fc,omitempty"`
}
