/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// Global settings for syslog servers.
type SyslogServerSettings struct {
	// The certificate of the certificate authority (CA) that signed the certificate(s) of the directory server, which is used to validate the authenticity of the configured servers.
	CaCertificate string `json:"ca_certificate,omitempty"`
	// Returns a value of `true` if messages that are necessary in order to audit TLS negotiations performed by the array are forwarded to the configured syslog servers.
	TlsAuditEnabled bool `json:"tls_audit_enabled,omitempty"`
}
