/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28VolumesPatchBody struct {
	// If set to `true`, destroys a resource. Once set to `true`, the `time_remaining` value will display the amount of time left until the destroyed resource is permanently eradicated. Before the `time_remaining` period has elapsed, the destroyed resource can be recovered by setting `destroyed=false`. Once the `time_remaining` period has elapsed, the resource is permanently eradicated and can no longer be recovered.
	Destroyed bool `json:"destroyed,omitempty"`
	// The new name for the resource.
	Name string `json:"name,omitempty"`
	// Moves the volume into the specified pod.
	Pod *interface{} `json:"pod,omitempty"`
	// Updates the virtual size of the volume. Measured in bytes.
	Provisioned int64 `json:"provisioned,omitempty"`
	// Sets QoS limits.
	Qos *interface{} `json:"qos,omitempty"`
	// Adds the volume to the specified volume group.
	VolumeGroup *interface{} `json:"volume_group,omitempty"`
	// Valid values are `promoted` and `demoted`. Patch `requested_promotion_state` to `demoted` to demote the volume so that the volume stops accepting write requests. Patch `requested_promotion_state` to `promoted` to promote the volume so that the volume starts accepting write requests.
	RequestedPromotionState string `json:"requested_promotion_state,omitempty"`
}
