/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type ArrayConnection struct {
	// A globally unique, system-generated ID. The ID cannot be modified and cannot refer to another resource.
	Id string `json:"id,omitempty"`
	// A locally unique, system-generated name. The name cannot be modified.
	Name string `json:"name,omitempty"`
	// Management IP address or FQDN of the target array.
	ManagementAddress string `json:"management_address,omitempty"`
	// IP addresses of the target arrays when `replication_transport` is `ip`. WWNs of the target arrays when `replication_transport` is `fc`.
	ReplicationAddresses []string `json:"replication_addresses,omitempty"`
	// Status of the connection. Valid values are `connected`, `connecting`, `partially_connected`, and `unbalanced`. A status of `connected` indicates that arrays are communicating. A status of `connecting` indicates that the array is trying to establish a connection. A status of `partially_connected` indicates that some replication addresses are communicating but others are not. A status of `unbalanced` indicates that the arrays are communicating, but the set of paths is either not redundant or not symmetric.
	Status string `json:"status,omitempty"`
	// The type of replication. Valid values are `async-replication` and `sync-replication`.
	Type_ string `json:"type,omitempty"`
	// The protocol used to transport data betwen the local array and the remote array. Valid values are `ip` and `fc`. The default is `ip`.
	ReplicationTransport string `json:"replication_transport,omitempty"`
	// The version of the target array.
	Version string `json:"version,omitempty"`
	Throttle *ArrayConnectionThrottle `json:"throttle,omitempty"`
}
