/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type ApiClient struct {
	// The unique identifier for the associated API client. The ID represents the JWT `aud` (audience) claim in ID Tokens issued for this API client.
	Id string `json:"id,omitempty"`
	// The API client name.
	Name string `json:"name,omitempty"`
	// The maximum role allowed for ID Tokens issued by this API client. The bearer of an access token will be authorized to perform actions within the intersection of this `max_role` and the role of the array user specified as the JWT `sub` (subject) claim. Valid `max_role` values are `readonly`, `ops_admin`, `array_admin`, and `storage_admin`. Users with the `readonly` (Read Only) role can perform operations that convey the state of the array. Read Only users cannot alter the state of the array. Users with the `ops_admin` (Ops Admin) role can perform the same operations as Read Only users plus enable and disable remote assistance sessions. Ops Admin users cannot alter the state of the array. Users with the `storage_admin` (Storage Admin) role can perform the same operations as Read Only users plus storage related operations, such as administering volumes, hosts, and host groups. Storage Admin users cannot perform operations that deal with global and system configurations. Users with the `array_admin` (Array Admin) role can perform the same operations as Storage Admin users plus array-wide changes dealing with global and system configurations. In other words, Array Admin users can perform all operations.
	MaxRole string `json:"max_role,omitempty"`
	// The name of the identity provider that will be issuing ID Tokens for this API client. This string represents the JWT `iss` (issuer) claim in ID Tokens issued for this API client.
	Issuer string `json:"issuer,omitempty"`
	// The API client's PEM formatted (Base64 encoded) RSA public key.
	PublicKey string `json:"public_key,omitempty"`
	// The unique identifier for the associated public key of this API client. This string must match the JWT `kid` (key ID) claim in ID Tokens issued for this API client.
	KeyId string `json:"key_id,omitempty"`
	// If `true`, the API client is permitted to exchange ID Tokens for access tokens. API clients are disabled by default.
	Enabled bool `json:"enabled,omitempty"`
	// The requested TTL (Time To Live) length of time for the exchanged access token. Measured in milliseconds.
	AccessTokenTtlInMs int64 `json:"access_token_ttl_in_ms,omitempty"`
}
