/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// The source of the software bundle.
type Model28SoftwarebundleBody struct {
	// The source of the software bundle. Accepts HTTP, HTTPS or FTP, and paths.
	Source string `json:"source,omitempty"`
}
