/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// SSL certificate managed by Purity//FA.
type InlineResponse20040Items struct {
	// The text of a new certificate signing request.
	CertificateSigningRequest string `json:"certificate_signing_request,omitempty"`
}
