/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type CloudProviderTag struct {
	// Key of the tag. Supports UTF-8 Unicode characters. Please refer to the offical document from cloud providers for limitations.
	Key string `json:"key,omitempty"`
	// Value of the tag. Supports UTF-8 Unicode characters. Please refer to the offical document from cloud providers for limitations.
	Value string `json:"value,omitempty"`
	// Details about the status of the tag if not healthy.
	Details string `json:"details,omitempty"`
}
