/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28AlertwatchersBody struct {
	// If set to `true`, email notifications will be sent to this watcher for alerts. If set to `false`, email notifications are disabled. If not specified, defaults to `true`.
	Enabled bool `json:"enabled,omitempty"`
}
