/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type DirectoryExport struct {
	// Returns a value of `true` if the managed directory of the export has been destroyed and is pending eradication. The export can be recovered by recovering the destroyed managed directory.
	Destroyed bool `json:"destroyed,omitempty"`
	// The managed directory of the export.
	Directory *AllOfDirectoryExportDirectory `json:"directory,omitempty"`
	// Returns a value of `true` if the export policy that manages this export is enabled.
	Enabled bool `json:"enabled,omitempty"`
	// The export name for accessing this export.
	ExportName string `json:"export_name,omitempty"`
	// The path of the exported managed directory.
	Path string `json:"path,omitempty"`
	// The export policy that manages this export. An export can be managed by at most one export policy.
	Policy *AllOfDirectoryExportPolicy `json:"policy,omitempty"`
}
