/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Kmip struct {
	// A locally unique, system-generated name. The name cannot be modified.
	Name string `json:"name,omitempty"`
	// The text of the CA certificate for the KMIP server.
	CaCertificate string `json:"ca_certificate,omitempty"`
	Certificate *KmipCertificate `json:"certificate,omitempty"`
	// List of URIs for the configured KMIP servers.
	Uris []string `json:"uris,omitempty"`
}
