/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type MaintenanceWindow struct {
	// A user-specified name. The name must be locally unique and can be changed.
	Name string `json:"name,omitempty"`
	// The maintenance window start time, measured in milliseconds since the UNIX epoch.
	Created int64 `json:"created,omitempty"`
	// The maintenance window end time, measured in milliseconds since the UNIX epoch.
	Expires int64 `json:"expires,omitempty"`
}
