/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28NetworkinterfacesBody struct {
	// A locally unique, system-generated name. The name cannot be modified.
	Name string `json:"name,omitempty"`
	Eth *Api28networkinterfacesEth `json:"eth,omitempty"`
	// The services provided by the specified network interface or Fibre Channel port.
	Services []string `json:"services,omitempty"`
}
