/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// Software upgrade attempt.
type Model28SoftwareinstallationsBody struct {
	// Mode the upgrade is in. Valid values are `check-only`, `interactive`, `semi-interactive`, and `one-click`. In `check-only` mode, the upgrade only runs pre-upgrade checks and returns. In `interactive` mode, the upgrade process pauses at several points, at which users must enter certain commands to proceed. In `semi-interactive` mode, the upgrade pauses if there are any upgrade check failures and functions like `one-click` mode otherwise. In `one-click` mode, the upgrade proceeds automatically without pausing.
	Mode string `json:"mode,omitempty"`
	// A list of upgrade checks whose failure is overridden during the upgrade. If any optional `args` are provided, they are validated later when the corresponding check script runs.
	OverrideChecks []Api28softwareinstallationsOverrideChecks `json:"override_checks,omitempty"`
}
