/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type InlineResponse400 struct {
	Error_ string `json:"error,omitempty"`
	ErrorDescription string `json:"error_description,omitempty"`
}
