/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// The v2c configurations of SNMP.
type Api28snmpagentsV2c struct {
	// Manager community ID under which Purity//FA is to communicate with the specified managers.
	Community string `json:"community,omitempty"`
}
