/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28SubnetsBody struct {
	// Returns a value of `true` if subnet is enabled. Returns a value of `false` if subnet is disabled. If not specified, defaults to `true`.
	Enabled bool `json:"enabled,omitempty"`
	// The IPv4 or IPv6 address of the gateway through which the specified subnet is to communicate with the network.
	Gateway string `json:"gateway,omitempty"`
	// Maximum message transfer unit (packet) size for the subnet in bytes. MTU setting cannot exceed the MTU of the corresponding physical interface. If not specified, defaults to `1500`.
	Mtu int32 `json:"mtu,omitempty"`
	// The IPv4 or IPv6 address to be associated with the specified subnet.
	Prefix string `json:"prefix,omitempty"`
	// VLAN ID number.
	Vlan int32 `json:"vlan,omitempty"`
}
