/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// Total bytes transmitted or received per second during resync replication. Resync replication is the mechanism to bring two arrays into sync. This may occur during an initial pod stretch, or, in case of outage, when two arrays reestablish connection. After the connection is restored, the array that was online starts replicating pod data to its peer array until the pod is once again in sync.
type PodPerformanceReplicationResyncBytesPerSec struct {
	// The number of bytes received per second from a remote array. The number will be zero if the arrays are unable to communicate.
	FromRemoteBytesPerSec int64 `json:"from_remote_bytes_per_sec,omitempty"`
	// The number of bytes transmitted per second to a remote array. The number will be zero if the arrays are unable to communicate.
	ToRemoteBytesPerSec int64 `json:"to_remote_bytes_per_sec,omitempty"`
	// Total bytes transmitted and received per second. The number will be zero if the arrays are unable to communicate.
	TotalBytesPerSec int64 `json:"total_bytes_per_sec,omitempty"`
}
