/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type AlertWatcher struct {
	// A locally unique, system-generated name. The name cannot be modified.
	Name string `json:"name,omitempty"`
	// If set to `true`, email notifications will be sent to this watcher for alerts. If set to `false`, email notification is disabled.
	Enabled bool `json:"enabled,omitempty"`
}
