/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28DirectorysnapshotsBody struct {
	// The client name portion of the client visible snapshot name. A full snapshot name is constructed in the form of `DIR.CLIENT_NAME.SUFFIX` where `DIR` is the managed directory name, `CLIENT_NAME` is the value of this field, and `SUFFIX` is the suffix. The client visible snapshot name is `CLIENT_NAME.SUFFIX`.
	ClientName string `json:"client_name,omitempty"`
	// The time to keep the snapshots for, in milliseconds.
	KeepFor int64 `json:"keep_for,omitempty"`
	// The suffix portion of the client visible snapshot name. A full snapshot name is constructed in the form of `DIR.CLIENT_NAME.SUFFIX` where `DIR` is the managed directory name, `CLIENT_NAME` is the client name, and `SUFFIX` is the value of this field. The client visible snapshot name is `CLIENT_NAME.SUFFIX`. If not specified, defaults to a monotonically increasing number generated by the system.
	Suffix string `json:"suffix,omitempty"`
}
