/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type SoftwareInstallationSteps struct {
	// A globally unique, system-generated ID. The ID cannot be modified.
	Id string `json:"id,omitempty"`
	// Name of the resource. The name cannot be modified.
	Name string `json:"name,omitempty"`
	// Start time in milliseconds since the UNIX epoch.
	StartTime int64 `json:"start_time,omitempty"`
	// End time in milliseconds since the UNIX epoch.
	EndTime int64 `json:"end_time,omitempty"`
	// A list of checks in this upgrade step.
	Checks []SoftwareInstallationStepsChecks `json:"checks,omitempty"`
	// Detailed description of the step.
	Description string `json:"description,omitempty"`
	// Detailed result of the step used to diagnose step failures.
	Details string `json:"details,omitempty"`
	// The version to which the current hop is upgrading.
	HopVersion string `json:"hop_version,omitempty"`
	Installation *SoftwareInstallationStepsInstallation `json:"installation,omitempty"`
	// Status of the step. Valid values are `running` and `finished`. A status of `running` indicates that the step has not finished. A status of `finished` indicates that the check has finished.
	Status string `json:"status,omitempty"`
}
