/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type InlineResponse200160 struct {
	// Displays a list of all items after filtering. The values are displayed for each name if meaningful. If `total_only=true`, the `items` list will be empty.
	Items []Volume `json:"items,omitempty"`
}
