/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Model28SoftwareinstallationsBody1 struct {
	// Adds the specified checks to the current list of override checks.
	AddOverrideChecks []Api28softwareinstallationsOverrideChecks `json:"add_override_checks,omitempty"`
}
