/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type PolicyMemberExport struct {
	// Returns a value of `true` if the member is destroyed.
	Destroyed bool `json:"destroyed,omitempty"`
	// Returns a value of `true` if the policy is enabled.
	Enabled bool `json:"enabled,omitempty"`
	// Reference to the resource that the policy is applied to.
	// REDDY
	Member *PolicyMember `json:"member,omitempty"`
	// Reference to the policy.
	Policy *Policy `json:"policy,omitempty"`
	// The export name for accessing this export.
	ExportName string `json:"export_name,omitempty"`
}
