/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Api28policiesnfsclientrulesRules struct {
	// Specifies access control for the export. Valid values are `root-squash` and `no-root-squash`. The default is `root-squash` if not specified.
	Access string `json:"access,omitempty"`
	// Specifies which clients are given access. Accepted notation includes IP, IP mask, or hostname. The default is `*` if not specified.
	Client string `json:"client,omitempty"`
	// Specifies which read-write client access permissions are allowed for the export. Valid values are `rw` and `ro`. The default is `rw` if not specified.
	Permission string `json:"permission,omitempty"`
}
