/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// Properties specific to the management service.
type DirectoryServiceManagement struct {
	// User login attribute in the structure of the configured LDAP servers. Typically the attribute field that holds the user's unique login name. Default value is `sAMAccountName` for Active Directory or `uid` for all other directory services.
	UserLoginAttribute string `json:"user_login_attribute,omitempty"`
	// Value of the object class for a management LDAP user. Defaults to `User` for Active Directory servers, `posixAccount` or `shadowAccount` for OpenLDAP servers dependent on the group type of the server, or `person` for all other directory servers.
	UserObjectClass string `json:"user_object_class,omitempty"`
}
