/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type SoftwareInstallations struct {
	// A globally unique, system-generated ID. The ID cannot be modified.
	Id string `json:"id,omitempty"`
	// Name of the resource. The name cannot be modified.
	Name string `json:"name,omitempty"`
	// Start time in milliseconds since the UNIX epoch.
	StartTime int64 `json:"start_time,omitempty"`
	// End time in milliseconds since the UNIX epoch.
	EndTime int64 `json:"end_time,omitempty"`
	// The `id` of the current step, or `null` if the upgrade is not active.
	CurrentStepId string `json:"current_step_id,omitempty"`
	// The detailed reason for the `status`.
	Details string `json:"details,omitempty"`
	// Mode that the upgrade is in. Valid values are `check-only`, `interactive`, `semi-interactive`, and `one-click`. In `check-only` mode, the upgrade only runs pre-upgrade checks and returns. In `interactive` mode, the upgrade process pauses at several points, at which users must enter certain commands to proceed. In `semi-interactive` mode, the upgrade pauses if there are any upgrade check failures, and functions like `one-click` mode otherwise. In `one-click` mode, the upgrade proceeds automatically without pausing.
	Mode string `json:"mode,omitempty"`
	// A list of upgrade checks whose failure is overridden during the upgrade. If any optional `args` are provided, they are validated later when the corresponding check script runs.
	OverrideChecks []Api28softwareinstallationsOverrideChecks `json:"override_checks,omitempty"`
	Software *SoftwareInstallationsSoftware `json:"software,omitempty"`
	// Status of the upgrade. Valid values are `installing`, `paused`, `aborting`, `aborted`, and `finished`. A status of `installing` indicates that the upgrade is running. A status of `paused` indicates that the upgrade is paused and waiting for user input. A status of `aborting` indicates that the upgrade is being aborted. A status of `aborted` indicates that the upgrade has stopped due to an abort. A status of `finished` indicates that the upgrade has finished successfully.
	Status string `json:"status,omitempty"`
}
