/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

type Session struct {
	// A globally unique, system-generated ID. The ID cannot be modified and cannot refer to another resource.
	Id string `json:"id,omitempty"`
	// A locally unique, system-generated name. The name cannot be modified.
	Name string `json:"name,omitempty"`
	// Date and time the user logged out of the Purity//FA interface. Not set if the session is still active.
	EndTime int64 `json:"end_time,omitempty"`
	// Description of session events such as login and user session. Valid values include `failed authentication`, `user session`, `login`, `logout`, `API token obtained`, and `request without session`.
	Event string `json:"event,omitempty"`
	// Number of session events.
	EventCount int32 `json:"event_count,omitempty"`
	// IP address of the user client connecting to the array or console if connected through local console.
	Location string `json:"location,omitempty"`
	// Method by which the user attempted to log in. Valid values include `API token`, `JWT`, `password`, and `public key`.
	Method string `json:"method,omitempty"`
	// Date and time the user logged in to the Purity//FA interface.
	StartTime int64 `json:"start_time,omitempty"`
	// Username of the Purity//FA user who triggered the user session event.
	User string `json:"user,omitempty"`
	// The user interface through which the user session event was performed. Valid values include `CLI`, `GUI`, and `REST`.
	UserInterface string `json:"user_interface,omitempty"`
}
