/*
 * FlashArray REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package pureclient

// Global settings for administrative accounts.
type AdminSettings struct {
	// The lockout duration, in milliseconds, if a user is locked out after reaching the maximum number of login attempts. Ranges from 1 second to 90 days.
	LockoutDuration int64 `json:"lockout_duration,omitempty"`
	// Maximum number of failed login attempts allowed before the user is locked out.
	MaxLoginAttempts int32 `json:"max_login_attempts,omitempty"`
	// Minimum password length. If not specified, defaults to 1.
	MinPasswordLength int32 `json:"min_password_length,omitempty"`
	// If `true`, then single sign-on is enabled for the array.
	SingleSignOnEnabled bool `json:"single_sign_on_enabled,omitempty"`
}
